/* Generated by @se373/typert-generator from the Host FaceModel — do not edit. */
import type {
  RemoteResult,
  TypertRemoteContribution,
} from '@se373/typert-protocol'
import type { BoardSnapshot } from '@se373/board-gateway/types'

declare module '@se373/typert-protocol' {
  interface TypertRemoteNamespace$626f617264 {
    snapshot: () => Promise<RemoteResult<BoardSnapshot>>
  }
  interface TypertRemoteMap {
    'board/snapshot': () => Promise<RemoteResult<BoardSnapshot>>
  }
  interface TypertRemoteNamespaceMap {
    'board': TypertRemoteNamespace$626f617264
  }
}

export declare const TYPERT_REMOTE: TypertRemoteContribution
export default TYPERT_REMOTE
//# sourceMappingURL=typert.remote-client.d.ts.map
