/* Generated by @se373/typert-generator from FaceModel — do not edit. */
import { z } from 'zod'

const GraphJsonValueRemoteCodec$schema = z.union([z.literal(null), z.string(), z.number(), z.literal(false), z.literal(true), z.array(z.lazy(() => GraphJsonValueRemoteCodec$schema)), z.record(z.string(), z.lazy(() => GraphJsonValueRemoteCodec$schema)).readonly()])
const _se373_board_gateway_board_snapshot_result$schema = z.object({
  'capturedAt': z.number(),
  'totalNodes': z.number(),
  'nodes': z.array(z.object({
  'entryId': z.string(),
  'parentEntryId': z.union([z.literal(null), z.string()]),
  'moduleName': z.string(),
  'uid': z.union([z.literal(null), z.number()]),
  'realm': z.string(),
  'structural': z.union([z.literal("row"), z.literal("group"), z.literal("include")]),
  'functional': z.union([z.literal(null), z.literal("provider"), z.literal("tools"), z.literal("listener")]),
  'lifecycle': z.union([z.literal(null), z.literal("pending"), z.literal("loading"), z.literal("active"), z.literal("failed"), z.literal("unloading")]),
  'enabled': z.boolean(),
  'mounted': z.boolean(),
  'provides': z.array(z.string()),
  'injects': z.array(z.string()),
  'unresolvedInjects': z.array(z.string()),
  'edges': z.array(z.object({
  'service': z.string(),
  'satisfied': z.boolean(),
  'providerEntryId': z.union([z.literal(null), z.string()]),
  'providerName': z.union([z.literal(null), z.string()]),
})),
  'transitions': z.array(z.object({
  'from': z.union([z.literal(null), z.literal("pending"), z.literal("loading"), z.literal("active"), z.literal("failed"), z.literal("unloading")]),
  'to': z.union([z.literal(null), z.literal("pending"), z.literal("loading"), z.literal("active"), z.literal("failed"), z.literal("unloading")]),
  'at': z.number(),
  'sn': z.number(),
})),
  'role': z.union([z.literal(null), z.literal("provider"), z.literal("seam"), z.literal("core"), z.literal("tool")]),
  'tier': z.union([z.literal(null), z.string()]),
  'label': z.union([z.literal(null), z.string()]),
  'config': z.union([z.literal(null), z.string(), z.number(), z.literal(false), z.literal(true), z.array(z.lazy(() => GraphJsonValueRemoteCodec$schema)), z.record(z.string(), z.lazy(() => GraphJsonValueRemoteCodec$schema)).readonly()]),
})),
})

export const TYPERT = {
  package: '@se373/board-gateway',
  face: 'host',
  schemas: [
  ],
  invocations: [
    {
      id: '@se373/board-gateway#board/snapshot',
      service: 'board',
      namespace: 'board',
      method: 'snapshot',
      invocation: { kind: 'direct' },
      parameters: [
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@se373/board-gateway/types#BoardSnapshot',
        schema: _se373_board_gateway_board_snapshot_result$schema,
      },
      sourceLocation: {"file":"packages/runtime/board-gateway/src/index.ts","line":50,"column":3},
    },
  ],
  model: {
    "services": [
      {
        "description": "Remote-only service exposing the runtime graph to browser surfaces.",
        "summary": "Remote-only service exposing the runtime graph to browser surfaces.",
        "tags": [],
        "jsDoc": "/** Remote-only service exposing the runtime graph to browser surfaces. */",
        "key": "board",
        "exportName": "BoardGateway",
        "members": [
          {
            "kind": "method",
            "name": "snapshot",
            "signature": "@Remote('snapshot') snapshot(): BoardSnapshot",
            "summary": "Project the whole tree.",
            "jsDoc": "/**\n * Project the whole tree.\n *\n * Unnarrowed on purpose. The narrowing `ctx.runtimeGraph.snapshot()` offers\n * exists so a *model* need not read 190 rows into its context; a board has\n * no such budget problem, and filtering in the browser keeps a filter change\n * from being a round trip.\n * @returns every configured row, disabled ones included.\n */"
          }
        ],
        "types": [
          {
            "name": "BoardEdge",
            "declaration": "export interface BoardEdge {\n    service: string;\n    satisfied: boolean;\n    providerEntryId: string | null;\n    providerName: string | null;\n}"
          },
          {
            "name": "BoardNode",
            "declaration": "export interface BoardNode {\n    entryId: string;\n    parentEntryId: string | null;\n    moduleName: string;\n    uid: number | null;\n    realm: string;\n    structural: StructuralKind;\n    functional: FunctionalKind | null;\n    lifecycle: LifecyclePhase;\n    enabled: boolean;\n    mounted: boolean;\n    provides: string[];\n    injects: string[];\n    unresolvedInjects: string[];\n    edges: BoardEdge[];\n    transitions: BoardTransition[];\n    role: NodeRole | null;\n    tier: string | null;\n    label: string | null;\n    config: GraphJsonValue;\n}"
          },
          {
            "name": "BoardSnapshot",
            "declaration": "export interface BoardSnapshot {\n    capturedAt: number;\n    totalNodes: number;\n    nodes: BoardNode[];\n}"
          },
          {
            "name": "BoardTransition",
            "declaration": "export interface BoardTransition {\n    from: LifecyclePhase;\n    to: LifecyclePhase;\n    at: number;\n    sn: number;\n}"
          },
          {
            "name": "FunctionalKind",
            "declaration": "export type FunctionalKind = (typeof FUNCTIONAL_KINDS)[number];"
          },
          {
            "name": "GraphJsonValue",
            "declaration": "export type GraphJsonValue = null | boolean | number | string | readonly GraphJsonValue[] | { readonly [key: string]: GraphJsonValue; };"
          },
          {
            "name": "LifecyclePhase",
            "declaration": "export type LifecyclePhase = (typeof LIFECYCLE_PHASES)[number] | null;"
          },
          {
            "name": "NodeRole",
            "declaration": "export type NodeRole = (typeof NODE_ROLES)[number];"
          },
          {
            "name": "StructuralKind",
            "declaration": "export type StructuralKind = (typeof STRUCTURAL_KINDS)[number];"
          }
        ]
      }
    ],
    "events": [],
    "objects": []
  },
}
