/**
 * The fabricated preset: an agent's own voice and tools, written as files.
 *
 * A fabricated agent's model-facing composition — persona, tool rows, and its
 * filesystem posture — is not mounted directly by the builder. It is written as
 * a preset directory in the agent's own workspace and mounted by the subtree's
 * own `agent-presets` row, because that is what scopes it: tools registered
 * under a preset's standing mount are visible only to sessions joined to it,
 * and a persona in a preset the main roster never lists can never appear in the
 * main builder's settings.
 *
 * The generated `agent.cordis.yml` is config, not prose — a wrong row here is a
 * silently different agent — so its generator is a pure function with a spec.
 *
 * @module @se373/builder/preset
 */
/** Serialize one YAML scalar, quoting anything that could read as syntax. */
function scalar(value) {
    if (typeof value === 'boolean' || typeof value === 'number')
        return String(value);
    const text = String(value);
    return /^[A-Za-z0-9@/._-]+$/.test(text) ? `'${text}'` : JSON.stringify(text);
}
/** Serialize a config object as indented YAML lines. */
function configLines(config, indent) {
    const lines = [];
    for (const [key, value] of Object.entries(config)) {
        if (value === undefined)
            continue;
        if (Array.isArray(value)) {
            lines.push(`${indent}${key}:`);
            for (const item of value)
                lines.push(`${indent}  - ${scalar(item)}`);
        }
        else if (value !== null && typeof value === 'object') {
            lines.push(`${indent}${key}:`);
            lines.push(...configLines(value, `${indent}  `));
        }
        else {
            lines.push(`${indent}${key}: ${scalar(value)}`);
        }
    }
    return lines;
}
/** Serialize one loader row. */
function rowLines(row) {
    const lines = [`- id: ${scalar(row.id)}`, `  name: ${scalar(row.name)}`];
    if (row.config !== undefined && Object.keys(row.config).length > 0) {
        lines.push('  config:');
        lines.push(...configLines(row.config, '    '));
    }
    return lines;
}
/**
 * The generated `agent.cordis.yml` for a fabricated agent.
 *
 * Row order is deliberate: persona first, because the system prompt sections
 * assemble in mount order; the filesystem realm before the tools that use it,
 * so `fs-sandbox` resolves the realm's policy rather than racing it; tools
 * last.
 * @param spec - the resolved agent.
 * @returns YAML text.
 */
export function renderAgentComposition(spec) {
    const lines = [
        `# Generated by @se373/builder for ${spec.name} v${spec.version}. Do not edit;`,
        '# plan a new version instead — this file is the composition a session joins,',
        '# and an edit here is a change no plan was approved for.',
        '',
        ...rowLines({ id: 'persona', name: '@se373/persona', config: { text: spec.persona } }),
        '',
    ];
    if (spec.filesystem !== null) {
        // The shape the shipped `inspect` preset proved: both rows share one
        // entry-local realm, because `fs-sandbox` resolves `sandboxPolicy` at
        // construction and a policy outside the realm would be the host's -- the
        // wrong workspace and the wrong mode.
        lines.push('- id: filesystem-realm', "  name: '@se373/cordis-plugin-group'", '  group: true', '  isolate:', '    fs: true', '    sandboxPolicy: true', '  config:', '    - id: sandbox-policy', "      name: '@se373/sandbox-policy'", '      config:', `        mode: ${scalar(spec.filesystem)}`, `        workspaceRoot: ${scalar(spec.workspaceRoot)}`, '    - id: fs-sandbox', "      name: '@se373/fs-sandbox'", '');
    }
    for (const row of spec.agentRows) {
        lines.push(...rowLines(row), '');
    }
    return `${lines.join('\n').trimEnd()}\n`;
}
/**
 * The generated `preset.yml` — display metadata only.
 * @param spec - the resolved agent.
 * @returns YAML text.
 */
export function renderPresetMetadata(spec) {
    return [
        `name: ${JSON.stringify(`${spec.name} v${spec.version}`)}`,
        `description: ${JSON.stringify(`Fabricated from ${spec.recipe ?? 'an explicit block list'}; scoped to this agent alone.`)}`,
        '',
    ].join('\n');
}
/**
 * The whole scaffold tree for one fabricated agent.
 * @param spec - the resolved agent.
 * @returns files by scaffold-relative path.
 */
export function scaffoldTree(spec) {
    return {
        [`preset/${spec.name}/preset.yml`]: renderPresetMetadata(spec),
        [`preset/${spec.name}/agent.cordis.yml`]: renderAgentComposition(spec),
        'workspace/': '',
    };
}
/** The row the builder adds to the subtree so the preset is mountable — and scoped. */
export function presetRosterRow(spec, presetRoot) {
    return {
        id: 'agent-presets',
        name: '@se373/agent-presets',
        config: {
            default: spec.name,
            // The main roster must never list this preset (its persona is this
            // agent's alone), and this roster must never pick up the user's own
            // authored presets either -- the composition a session joins should be
            // exactly what the approved plan said.
            includeUserRoot: false,
            roots: [{ path: presetRoot, trust: 'user' }],
        },
        block: 'builtin:agent-presets',
    };
}
//# sourceMappingURL=preset.js.map